# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliases',
                'verbose_name': 'alias',
                'verbose_name_plural': 'aliases',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128, unique=True, verbose_name='domain')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='description')),
                ('active', models.BooleanField(default=False, verbose_name='is active')),
                ('aliases', models.BooleanField(default=False, verbose_name='allow aliases')),
                ('mailboxes', models.BooleanField(default=False, verbose_name='has mailboxes')),
                ('backupmx', models.BooleanField(default=False, verbose_name='backup MX records')),
                ('transport', models.CharField(blank=True, max_length=128, null=True, verbose_name='transport')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Required. 255 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=255, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('maildir', models.CharField(max_length=128, verbose_name='mail directory')),
                ('quote', models.PositiveIntegerField(default=0, verbose_name='quote')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_postfix.Domain')),
            ],
            options={
                'db_table': 'mailboxes',
                'verbose_name': 'mail box',
                'verbose_name_plural': 'mail boxes',
            },
        ),
        migrations.AddField(
            model_name='alias',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_postfix.Domain'),
        ),
        migrations.AddField(
            model_name='alias',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_postfix.Mailbox'),
        ),
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together=set([('domain', 'username')]),
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set([('alias', 'mailbox')]),
        ),
    ]
